default: &default
  adapter: postgresql
  host : localhost
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ang
  username: postgres
  password: postgres

test:
  <<: *default
  database: ang
  username: postgres
  password: postgres


