# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81c94f278a6ea2160f593a9e1d16ccabc7a8f968f1ac63c502de3abf4022fabf2b4bc32c765ac6933885d574c3192fd1d56bc87178a054fcf76f17956d2d10ff

test:
  secret_key_base: 362e2c1febc2f06a9e29bed192d37297aed826ddd68ec09713929334f9a0aa4608c656c2ea0cb70ae9bf3f11da3ab6b11adc86a9b87a6a60e88c07c0220bc354

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
